name: All You Need
main: com.crystalcraftmc.allyouneed.Main
version: 1.0
load : POSTWORLD
authors: [Beben107700, jflory7]

commands:
  ct:
    description: Open crafting table
    usage: /ct
    permission: ayn.ct
    aliases: [craft]
  ender:
    description: Open ender chest
    usage: /ender
    permission: ayn.ender
    aliases: [ender]
  tp:
    description: Teleport to another player
    usage: /tp <Player>
    permission: ayn.tpgo
    aliases: [teleport]
  tphere:
    descritpion: Teleport another player to you
    usage: /tphere <Player>
    permission: ayn.tpgo
  tppos:
    description: Teleport to a specific position
    usage: /tppos <X> <Y> <Z>
    permission: ayn.tpgo
    aliases: [tpcoord, tploc]
  mypos:
    description: Check your location
    usage: /mypos
    permission: ayn.mypos
    aliases: [myloc, mylocation, where, checkpos]
  setspawn:
    description: Set the world spawn
    usage: /setspawn
    permission: ayn.definespawn
    aliases: [definespawn]
  spawn:
    description: Go to the world spawn
    usage: /spawn
    permission: ayn.spawn
  home:
    description: Go home
    usage: /home
    permission: ayn.home
  sethome:
    description: Define your home
    usage: /sethome
    permission: ayn.sethome
    aliases: [definehome]
  heal:
    description: Heals you or a player
    usage: /heal [player]
    permission: ayn.heal
  rules:
    description: Displays the server rules
    usage: /rules
    permission: ayn.rules
  kickall:
    description: Kick all players
    usage: /kickall [reason]
    permission: ayn.kickall
    aliases: [gtfoall, allgtfo]
  fly:
    description: Fly
    usage: /fly (player)
    permission: ayn.fly
    aliases: [iwannafly]
  hat:
    description: Put a hat on your head
    usage: /hat
    permission: ayn.hat
  tell:
    description: Whisper messages to friends
    usage: /tell <Player> <Message>
    permission: ayn.tell
    aliases: [msg, tell, r]
  repair:
    description: Repair the item you are holding
    usage: /repair
    permission: ayn.repair

    
permissions:
  ayn.*:
    children:
      ayn.ct: true
      ayn.ender: true
      ayn.tpgo: true
      ayn.definespawn: true
      ayn.spawn: true
      ayn.home: true
      ayn.definehome: true
      ayn.heal: true
      ayn.rules: true
      ayn.usebannedblocks: true
      ayn.kickall: true
      ayn.fly: true
      ayn.mypos: true
      ayn.hat: true
      ayn.tell: true
      ayn.repair: true
  ayn.ct:
    default: op
  ayn.ender:
    default: op
  ayn.tpgo:
    default: op
  ayn.definespawn:
    default: op
  ayn.spawn:
    default: op
  ayn.home:
    default: op
  ayn.sethome:
    default: op
  ayn.heal:
    default: op
  ayn.usebannedblocks:
    default: op
  ayn.rules:
    default: op
  ayn.kickall:
    default: op
  ayn.fly:
    default: op
  ayn.mypos:
    default: op
  ayn.hat:
    default: op
  ayn.tell:
    default: true
  ayn.repair:
    default: op
